namespace Almatter.App.Localization;

public sealed partial class Strings
{
    public static Strings French { get; } = new()
    {
        // ── Login window ─────────────────────────────────────────────
        LoginWindowTitle = "Almatter — Connexion",
        LoginHeading = "Se connecter à Almatter",
        LoginServer = "Serveur",
        LoginServerPlaceholder = "https://mon-serveur.exemple.com",
        LoginId = "Identifiant",
        LoginIdPlaceholder = "Nom d'utilisateur ou e-mail",
        LoginPassword = "Mot de passe",
        LoginButton = "Se connecter",
        LoginBusy = "Connexion…",
        LoginFailed = error => $"Connexion impossible : {error}",

        // ── Sidebar ──────────────────────────────────────────────────
        Search = "Rechercher",
        FavoritesHeader = "FAVORIS",
        FavoritesEmptyHint = "Glisse un canal ou une conversation ici",
        ChannelsHeader = "CANAUX",
        BrowseChannels = "Parcourir les canaux",
        DirectMessagesHeader = "MESSAGES PRIVÉS",
        NewConversation = "Nouvelle conversation",
        ChangeStatus = "Changer de statut",
        ChannelMute = "Mettre en sourdine",
        ChannelUnmute = "Réactiver les notifications",
        ChannelRename = "Renommer pour moi…",
        ChannelRestoreName = "Rétablir le nom d'origine",
        ChannelMutedTip = "En sourdine",
        OriginalNameLabel = "Nom d'origine : ",

        // ── Presence ─────────────────────────────────────────────────
        StatusOnline = "Disponible",
        StatusAway = "Absent",
        StatusDoNotDisturb = "Ne pas déranger",
        StatusOffline = "Hors ligne",

        // ── Conversation ─────────────────────────────────────────────
        PinnedMessages = "Messages épinglés",
        SendMessage = "Envoyer un message",
        WriteInChannel = channel => $"Écrire dans #{channel}…",
        Sending = "Envoi en cours…",
        Pinned = "Épinglé",
        Edited = "(modifié)",
        Open = "Ouvrir",
        Downloading = "Téléchargement…",
        ReplyCount = count => count == 1 ? "1 réponse" : $"{count} réponses",
        Edit = "Modifier",
        Delete = "Supprimer",
        AddReaction = "Ajouter une réaction",
        Reply = "Répondre",
        PinToChannel = "Épingler au canal",
        UnpinFromChannel = "Détacher du canal",
        JumpToLatest = "Revenir au dernier message",
        EditingMessage = "Modification du message",
        Cancel = "Annuler",
        Close = "Fermer",
        Save = "Enregistrer",
        AttachFile = "Joindre un fichier",
        AttachFilesDialogTitle = "Joindre un ou plusieurs fichiers",
        InsertEmoji = "Insérer un émoji",
        Formatting = "Mise en forme",
        Thread = "Fil de discussion",
        ReplyToThreadPlaceholder = "Répondre au fil…",
        ConnectingToServer = "Connexion au serveur…",
        LoadingTeamsAndChannels = "Récupération des équipes et des canaux",
        CopyLink = "Copier le lien",
        CopyMessageLink = "Copier le lien vers ce message",
        MessageLinkCopied = "Lien copié",
        DeleteMessageQuestion = "Supprimer ce message ?",
        Today = "Aujourd'hui",
        Yesterday = "Hier",
        DaySeparatorFormat = "dddd d MMMM",
        DaySeparatorFormatWithYear = "dddd d MMMM yyyy",
        SearchResultTimeFormat = "dd/MM/yy HH:mm",
        FileSizeUnits = ["o", "Ko", "Mo", "Go"],
        TypingOne = name => $"{name} est en train d'écrire…",
        TypingTwo = (first, second) => $"{first} et {second} sont en train d'écrire…",
        TypingMany = "Plusieurs personnes sont en train d'écrire…",

        // ── Reactions ────────────────────────────────────────────────
        You = "Vous",
        OtherPeople = count => count == 1 ? "1 autre" : $"{count} autres",
        JoinLastName = (others, last) => $"{others} et {last}",
        // Any list including "Vous" takes "avez", whatever else is in it.
        ReactedWith = (who, includesYou, count, emoji) =>
            $"{who} {(includesYou ? "avez" : count == 1 ? "a" : "ont")} réagi avec :{emoji}:",

        // ── Formatting toolbar ───────────────────────────────────────
        FormatBold = "Gras (Ctrl+B)",
        FormatItalic = "Italique (Ctrl+I)",
        FormatStrikethrough = "Barré (Ctrl+Maj+X)",
        FormatHeading = "Titre",
        FormatQuote = "Citation",
        FormatBulletList = "Liste à puces",
        FormatNumberedList = "Liste numérotée",
        FormatCode = "Code",
        FormatCodeBlock = "Bloc de code",
        FormatLink = "Lien (Ctrl+Alt+K)",
        FormatRule = "Ligne de séparation",
        FormatTable = "Tableau",
        LinkTextPlaceholder = "texte du lien",
        TableColumn = number => $"Colonne {number}",

        // ── Panels ───────────────────────────────────────────────────
        SearchPersonPlaceholder = "Rechercher une personne…",
        Searching = "Recherche…",
        NoPersonMatches = "Personne ne correspond",
        FilterByNamePlaceholder = "Filtrer par nom…",
        LoadingChannels = "Chargement des canaux…",
        NoChannelsToJoin = "Aucun canal public à rejoindre",
        Join = "Rejoindre",
        SearchMessagePlaceholder = "Rechercher un message…",
        NoResults = "Aucun résultat",
        NoPinnedMessages = "Aucun message épinglé dans ce canal. Survolez un message et utilisez l'épingle pour en garder un sous la main.",
        GoToMessage = "Aller à ce message",
        RenameForMe = "Renommer pour moi",
        RenamePlaceholder = "Laisser vide pour garder le nom d'origine",
        RenameOnlyYou = "Seul vous verrez ce nom.",

        // ── Emoji picker ─────────────────────────────────────────────
        ChooseReaction = "Choisir une réaction",
        SearchEmojiPlaceholder = "Rechercher un émoji…",
        SkinToneHeader = "TEINT",
        NoEmojiMatches = "Aucun émoji ne correspond",
        MostUsedEmoji = "LES PLUS UTILISÉS",
        StandardEmoji = "STANDARD",
        CustomEmoji = "PERSONNALISÉS",
        SkinToneDefault = "Par défaut",
        SkinToneLight = "Clair",
        SkinToneMediumLight = "Moyen clair",
        SkinToneMedium = "Moyen",
        SkinToneMediumDark = "Moyen foncé",
        SkinToneDark = "Foncé",

        // ── Settings ─────────────────────────────────────────────────
        SettingsTitle = "Réglages",
        SettingsLanguage = "LANGUE",
        SettingsAppearance = "APPARENCE",
        ThemeSystem = "Système",
        ThemeLight = "Clair",
        ThemeDark = "Sombre",
        ThemeSystemHint = "« Système » suit le réglage clair/sombre de Windows.",
        ReducedContrast = "Réduire le contraste",
        ReducedContrastHint = "Texte et fonds plus doux, pour les longues sessions.",
        SettingsFont = "POLICE",
        FontSystem = "Système",
        FontMattermostHint = "« Mattermost » utilise Open Sans, la police du client officiel.",
        SettingsMessageFontSize = "TAILLE DE POLICE DES MESSAGES",
        FontSizeSmall = "Petite",
        FontSizeNormal = "Normale",
        FontSizeLarge = "Grande",
        SettingsNotifications = "NOTIFICATIONS",
        SoundForAllMessages = "Son pour tous les messages",
        SoundForAllMessagesHint = "Sinon, seules les notifications 🔔 qui vous sont destinées font du bruit.",
        SettingsLinks = "LIENS",
        LinkPreviews = "Aperçus de liens",
        LogOut = "Se déconnecter",

        // ── Notifications and taskbar ────────────────────────────────
        Someone = "Quelqu'un",
        ReactedToYourMessage = emoji => $"a réagi {emoji} à votre message",
        ReactedToQuote = (emoji, quote) => $"a réagi {emoji} à « {quote} »",
        TaskbarNewMessages = "Nouveaux messages",
        TaskbarNotifications = count => count == 1 ? "1 notification" : $"{count} notifications",

        // ── Errors ───────────────────────────────────────────────────
        UnexpectedError = error => $"Erreur inattendue : {error}",
        UnknownTeam = "Équipe inconnue — reconnectez-vous.",
        NoTeamFound = "Aucune équipe trouvée pour ce compte.",
        NoChannelFound = "Aucun canal trouvé pour cette équipe.",
        UnknownChannel = "Canal inconnu",
        UnknownUser = "Utilisateur inconnu",
        ErrorConnectionInterrupted = "La connexion au serveur a été coupée pendant la réception de la réponse. Réessayez.",
        ErrorUnreadableResponse = path => $"Le serveur a renvoyé une réponse que l'app ne sait pas lire ({path}).",
        ErrorSessionExpired = "Votre session a expiré. Reconnectez-vous pour continuer.",
    };
}
