namespace Almatter.App.Localization;

public sealed partial class Strings
{
    public static Strings English { get; } = new()
    {
        // ── Login window ─────────────────────────────────────────────
        LoginWindowTitle = "Almatter — Sign in",
        LoginHeading = "Sign in to Almatter",
        LoginServer = "Server",
        LoginServerPlaceholder = "https://my-server.example.com",
        LoginId = "Login",
        LoginIdPlaceholder = "Username or email",
        LoginPassword = "Password",
        LoginButton = "Sign in",
        LoginBusy = "Signing in…",
        LoginFailed = error => $"Could not sign in: {error}",

        // ── Sidebar ──────────────────────────────────────────────────
        Search = "Search",
        FavoritesHeader = "FAVORITES",
        FavoritesEmptyHint = "Drag a channel or conversation here",
        ChannelsHeader = "CHANNELS",
        BrowseChannels = "Browse channels",
        DirectMessagesHeader = "DIRECT MESSAGES",
        NewConversation = "New conversation",
        ChangeStatus = "Set status",
        ChannelMute = "Mute",
        ChannelUnmute = "Unmute",
        ChannelRename = "Rename for me…",
        ChannelRestoreName = "Restore original name",
        ChannelMutedTip = "Muted",
        OriginalNameLabel = "Original name: ",

        // ── Presence ─────────────────────────────────────────────────
        StatusOnline = "Online",
        StatusAway = "Away",
        StatusDoNotDisturb = "Do not disturb",
        StatusOffline = "Offline",

        // ── Conversation ─────────────────────────────────────────────
        PinnedMessages = "Pinned messages",
        SendMessage = "Send a message",
        WriteInChannel = channel => $"Write to #{channel}…",
        Sending = "Sending…",
        Pinned = "Pinned",
        Edited = "(edited)",
        Open = "Open",
        Downloading = "Downloading…",
        ReplyCount = count => count == 1 ? "1 reply" : $"{count} replies",
        Edit = "Edit",
        Delete = "Delete",
        AddReaction = "Add a reaction",
        Reply = "Reply",
        PinToChannel = "Pin to channel",
        UnpinFromChannel = "Unpin from channel",
        JumpToLatest = "Jump to latest message",
        EditingMessage = "Editing message",
        Cancel = "Cancel",
        Close = "Close",
        Save = "Save",
        AttachFile = "Attach a file",
        AttachFilesDialogTitle = "Attach one or more files",
        InsertEmoji = "Insert an emoji",
        Formatting = "Formatting",
        Thread = "Thread",
        ReplyToThreadPlaceholder = "Reply to thread…",
        ConnectingToServer = "Connecting to the server…",
        LoadingTeamsAndChannels = "Fetching teams and channels",
        CopyLink = "Copy link",
        CopyMessageLink = "Copy link to this message",
        MessageLinkCopied = "Link copied",
        DeleteMessageQuestion = "Delete this message?",
        Today = "Today",
        Yesterday = "Yesterday",
        DaySeparatorFormat = "dddd, MMMM d",
        DaySeparatorFormatWithYear = "dddd, MMMM d, yyyy",
        SearchResultTimeFormat = "MMM d, yyyy HH:mm",
        FileSizeUnits = ["B", "KB", "MB", "GB"],
        TypingOne = name => $"{name} is typing…",
        TypingTwo = (first, second) => $"{first} and {second} are typing…",
        TypingMany = "Several people are typing…",

        // ── Reactions ────────────────────────────────────────────────
        You = "You",
        OtherPeople = count => count == 1 ? "1 other" : $"{count} others",
        JoinLastName = (others, last) => $"{others} and {last}",
        ReactedWith = (who, _, _, emoji) => $"{who} reacted with :{emoji}:",

        // ── Formatting toolbar ───────────────────────────────────────
        FormatBold = "Bold (Ctrl+B)",
        FormatItalic = "Italic (Ctrl+I)",
        FormatStrikethrough = "Strikethrough (Ctrl+Shift+X)",
        FormatHeading = "Heading",
        FormatQuote = "Quote",
        FormatBulletList = "Bulleted list",
        FormatNumberedList = "Numbered list",
        FormatCode = "Code",
        FormatCodeBlock = "Code block",
        FormatLink = "Link (Ctrl+Alt+K)",
        FormatRule = "Horizontal line",
        FormatTable = "Table",
        LinkTextPlaceholder = "link text",
        TableColumn = number => $"Column {number}",

        // ── Panels ───────────────────────────────────────────────────
        SearchPersonPlaceholder = "Search for someone…",
        Searching = "Searching…",
        NoPersonMatches = "No one matches",
        FilterByNamePlaceholder = "Filter by name…",
        LoadingChannels = "Loading channels…",
        NoChannelsToJoin = "No public channels to join",
        Join = "Join",
        SearchMessagePlaceholder = "Search messages…",
        NoResults = "No results",
        NoPinnedMessages = "No pinned messages in this channel. Hover over a message and use the pin to keep it at hand.",
        GoToMessage = "Go to this message",
        RenameForMe = "Rename for me",
        RenamePlaceholder = "Leave empty to keep the original name",
        RenameOnlyYou = "Only you will see this name.",

        // ── Emoji picker ─────────────────────────────────────────────
        ChooseReaction = "Choose a reaction",
        SearchEmojiPlaceholder = "Search emoji…",
        SkinToneHeader = "SKIN TONE",
        NoEmojiMatches = "No matching emoji",
        MostUsedEmoji = "MOST USED",
        StandardEmoji = "STANDARD",
        CustomEmoji = "CUSTOM",
        SkinToneDefault = "Default",
        SkinToneLight = "Light",
        SkinToneMediumLight = "Medium-light",
        SkinToneMedium = "Medium",
        SkinToneMediumDark = "Medium-dark",
        SkinToneDark = "Dark",

        // ── Settings ─────────────────────────────────────────────────
        SettingsTitle = "Settings",
        SettingsLanguage = "LANGUAGE",
        SettingsAppearance = "APPEARANCE",
        ThemeSystem = "System",
        ThemeLight = "Light",
        ThemeDark = "Dark",
        ThemeSystemHint = "“System” follows the Windows light/dark setting.",
        ReducedContrast = "Reduce contrast",
        ReducedContrastHint = "Softer text and backgrounds, for long sessions.",
        SettingsFont = "FONT",
        FontSystem = "System",
        FontMattermostHint = "“Mattermost” uses Open Sans, the official client's font.",
        SettingsMessageFontSize = "MESSAGE FONT SIZE",
        FontSizeSmall = "Small",
        FontSizeNormal = "Normal",
        FontSizeLarge = "Large",
        SettingsNotifications = "NOTIFICATIONS",
        SoundForAllMessages = "Sound for every message",
        SoundForAllMessagesHint = "Otherwise only the 🔔 notifications meant for you make a sound.",
        SettingsLinks = "LINKS",
        LinkPreviews = "Link previews",
        LogOut = "Sign out",

        // ── Notifications and taskbar ────────────────────────────────
        Someone = "Someone",
        ReactedToYourMessage = emoji => $"reacted {emoji} to your message",
        ReactedToQuote = (emoji, quote) => $"reacted {emoji} to “{quote}”",
        TaskbarNewMessages = "New messages",
        TaskbarNotifications = count => count == 1 ? "1 notification" : $"{count} notifications",

        // ── Errors ───────────────────────────────────────────────────
        UnexpectedError = error => $"Unexpected error: {error}",
        UnknownTeam = "Unknown team — please sign in again.",
        NoTeamFound = "No team found for this account.",
        NoChannelFound = "No channel found for this team.",
        UnknownChannel = "Unknown channel",
        UnknownUser = "Unknown user",
        ErrorConnectionInterrupted = "The connection to the server dropped while the answer was arriving. Please try again.",
        ErrorUnreadableResponse = path => $"The server sent an answer this app cannot read ({path}).",
    };
}
